server {
    listen 80;
    server_name magixun.beverg.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name magixun.beverg.com;

    ssl_certificate /etc/letsencrypt/live/magixun.beverg.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/magixun.beverg.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    access_log /var/log/nginx/magixun.beverg.com_access.log;
    error_log /var/log/nginx/magixun.beverg.com_error.log;

    # 微信验证文件
    location = /MP_verify_sVqIlVL7Wx5orjph.txt {
        alias /opt/ass/public/MP_verify_sVqIlVL7Wx5orjph.txt;
        default_type text/plain;
    }

    location / {
        proxy_pass http://localhost:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}